"""Mirror the validated runtime increment; do not deploy unvalidated source."""
from pathlib import Path
import hashlib, json, shutil
from deploy_local import ROOT, SOURCE, TARGET, inventory, main as verify

def document(record,sync):
 lines=['# Balkan rearmament implementation — 0.16.0','',
 'The primary installed mod was upgraded and checked before source synchronization. The 45-path increment adds 43 new paths and updates only the two existing descriptors; all 557 other previously installed files retain their hashes. The sibling launcher descriptor is also updated and retains Workshop identity 3813570241. All 602 installed/source files match. No game window or save was touched.','',
 '## 1. Local playable files and GitHub mirror','',
 'These exact relative game paths were installed into `C:/Users/Balazs/Documents/Paradox Interactive/Hearts of Iron IV/mod/make_serbia_great_again` and then copied unchanged to the repository game folder. Absolute paths and SHA-256 hashes are in `balkan_rearmament_sources.json`; all-file equality is in `balkan_rearmament_sync.json`.','']
 lines += ['- `'+p+'`' for p in record['changed_relative_paths']]
 lines += ['', 'The sibling `make_serbia_great_again.mod` launcher points to the primary runtime. GitHub additionally receives the installer, validator, synchronizer, these reports and AGENTS workflow entry; `validation_history.py` recognizes exact approved hashes. `validate_bosnia.py` now unwraps existing decision-presentation wrappers before its old comparison, using the existing normalizer. No Bosnia gameplay file changed.','', '## 2–3. Focus IDs','', '| Country | Focus ID | Days | Prerequisites |','| --- | --- | --- | --- |']
 lines += ['| '+r['tag']+' | `'+r['id']+'` | '+str(r['days'])+' | '+', '.join('`'+p+'`' for p in r['parents'])+' |' for r in record['focuses']]
 lines += ['', 'Both countries previously selected TFR’s empty generic tree. New country-scored mini-trees preserve that generic definition and every unrelated country tree. Existing saves still on `generic_focus` receive the appropriate tree on startup with completed focuses kept. Existing special focus contexts are not forcibly replaced. Each focus has an authored reward tooltip and a guarded real reward or concrete contract unlock; there are no placeholder focuses. Croatian peaceful and emergency phases are independent roots, allowing the AI to pivot without first completing the peaceful programme.','', '## 4. National spirit IDs','', '| ID | Name | Modifiers |','| --- | --- | --- |']
 for stem,(title,art,mods) in record['ideas'].items():lines.append('| `MSGA_'+stem+'` | '+title+' | '+', '.join('`'+k+' = '+str(v)+'`' for k,v in mods.items())+' |')
 lines += ['', 'Workshop expansion, Albanian ammunition, Croatian business confidence, emergency construction and Western procurement support are exactly 180 days. Armed Albania replaces Battalion Readiness, retaining +5% organisation rather than stacking another +5%; final defence and mobilisation bonuses remain modest. Four supplied national-spirit compositions are reused for fourteen coherent programme icons.','', '## 5, 10–11. One-time contracts and exact equipment','', '| Decision ID | Treasury $B | Days | Required focus | Exact delivery (type / amount / producer) |','| --- | --- | --- | --- | --- |']
 for tag,stem,title,cost,days,focus,items,icon in record['contracts']:
  lines.append('| `MSGA_'+tag+'_'+stem+'` | '+str(cost)+' | '+str(days)+' | `MSGA_'+tag+'_'+focus+'` | '+'; '.join('`'+typ+'` / '+str(amount)+' / '+producer for typ,amount,producer in items)+' |')
 lines += ['', '**German DLC adaptation:** with No Step Back, the German contract delivers 40 `modern_tank_chassis_1`, producer GER, `variant_name = "Leopard 2A5"`, referring to the already existing TFR German design. Without NSB it delivers 40 `modern_tank_equipment_3`. Germany must exist at start and delivery; disappearance cancels/refunds the pending contract. The native `variant_name` stockpile syntax is also used in the installed game’s Ethiopian equipment-delivery event. No variant or equipment ID was invented.','',
 'Each start callback checks Treasury, focus completion, country status, the completed marker and a shared pending-shipment lock before reserving `income_var_temp = -cost` through native `add_income`. Persistent pending flags survive model serialization. Delivery requires that pending flag and absence of the completed flag, adds equipment once, sets a permanent completed marker and releases reservations. Cancellation refunds once and permits a fresh attempt; completing a purchase permanently hides it and prevents any subsequent charge/reward. There are no cooldown purchases or repeatable contracts. Cost is Treasury rather than PP (native decision `cost = 0`). Tooltips state price, days, equipment, unlock requirements and one-time nature.','',
 'Direct focus deliveries:','',
 '- `MSGA_ALB_empty_the_old_depots`: 1500 `infantry_equipment_1` (SOV), 60 `artillery_equipment_1` (SOV), 75 `support_equipment_1` (ALB).',
 '- `MSGA_ALB_domestic_ammunition`: 25 `support_equipment_1` (ALB).',
 '- `MSGA_CRO_modernise_the_army`: 50 `support_equipment_1` (CRO).',
 '- `MSGA_CRO_expand_hs_produkt`: 1200 `infantry_equipment_2` (CRO).',
 '- `MSGA_CRO_mass_arms_production`: 2200 `infantry_equipment_2`, 120 `support_equipment_1`, 60 `artillery_equipment_1` (all CRO).','',
 '## 6–8. Starting industry and Croatian template','',
 'Croatia Proper is state **109**, despite its native filename `109-Eastern Croatia.txt`. It originally has **0** MIL. Its history now has **2** MIL; the existing **1** MIL in Dalmatia (103) is retained, giving **3 nationally**. No factory is moved. Ownership, cores, infrastructure, civilian/office buildings, slots and every other state-history field are preserved. Factories are not granted by startup logic and cannot duplicate on reload. Albania retains exactly **1 starting MIL**, its native country/state history and its original two formations. These starting-history/OOB changes require a fresh campaign.','',
 'The internal and displayed new template name is **Croatian Light Infantry**; the English localization reference is `MSGA_CRO_light_infantry`. Its exact definition is:','',
 '```hoi4',record['CRO_template']['definition'],'```','',
 'Native battalion keys: `infantry` at (0,0) and (0,1), and `artillery_brigade` at (1,0). `infantry` belongs to the native infantry regiment group and `category_light_infantry`; Croatia’s existing `infantry_weapons1` technology enables it. The artillery uses the native artillery regiment. The support block is empty. The original OOB definitions and original two armoured/mechanised divisions are unchanged; no extra unit is spawned. A moderate Croatian-only native AI template entry uses role `infantry`, 2+1 target regiments, no support, high match requirement and no in-field upgrade, supporting affordable recruitment while retaining the original formations. Equipment/manpower availability still governs actual training. Separate screenshot files were not supplied; the task’s explicit composition and native state data were the implementation references.','',
 '## 9. Bosnian-war unlock','',
 '`MSGA_croatian_bosnia_escalation = { SER = { has_country_flag = MSGA_bosnia_intervened } }`. Existing `MSGA_join_srpska_war` sets that flag only after native same-war intervention succeeds and `has_war_with = BOS` becomes true. It is not the earlier `MSGA_bosnian_war_started` uprising flag. The intervention marker persists through scripted settlement, so the Croatian branch does not vanish when the Bosnia war ends. Every emergency focus requires this marker. Before intervention the branch is unavailable. After intervention emergency AI weights are 550–1000 and peaceful weights drop by a factor of 0.01; peaceful focuses remain accessible. No Serbia/Bosnia event or settlement was altered.','',
 '## 12–18. Actual production lock, native files, override and safeguards','',
 'TFR’s `common/on_actions/00_TFR_on_actions_ZZZ_startup.txt` selects AI countries with `is_relavent_tag = no` and executes three restrictions: `add_ideas = ai_disabled_production`, `country_lock_all_division_template = yes`, and `set_research_slots = 0`. The hidden idea is in `common/ideas/TFR_ideas_ZZZ_mishmash.txt`: construction speed, military output and dockyard output are each -9999; consumer goods factor is +10 and conscription is -1. Removing its label alone would change nothing.','',
 'The relevance trigger is defined in `common/scripted_triggers/00_TFR_scripted_triggers_ZZZ_generic.txt`. MSGA overrides that one file with only seven extra tag clauses in the existing relevance OR. All other trigger definitions are identical to upstream. This prevents the startup triple lock and enables native low-factory AI and economic decision/strategy systems in `common/ai_strategy/TFR_ai_strategy_ZZZ.txt` and `common/on_actions/00_TFR_on_actions_ZZZ_money.txt`, without altering other tags. No original TFR installation file was edited.','',
 'Exact whitelist: **SLV** Slovenia; **CRO** Croatia; **BOS** Bosnia and Herzegovina; **MNT** Montenegro; **KOS** Kosovo; **ALB** Albania; **MAC** Macedonia. HRZ is a separate native tag and is not silently added to the requested whitelist.','',
 'For an existing save, country-scoped startup cleanup removes the real hidden idea, clears the country-level template lock using the same native command with `no`, and restores the native 3/4 research slots only if the current count is zero. Existing extra research slots are retained. A weekly guard acts only if the restriction exists again or the one-time restoration flag is absent. There is no daily polling and no factory/army grant in cleanup.','',
 'The installed TFR search finds production-lock additions only in generic startup and `common/decisions/TFR_decisions_ISR.txt`; the latter is scoped to Israel/Middle Eastern countries, not the seven tags. Country-template lock paths in generic/US startup, USA effects, the English/Syrian events and French victory are country-specific and were inspected; no later Balkan-specific relock path was found. Weekly restoration removes any renewed hidden production idea. The targeted validator checks the exact native override, all startup commands, all current production-idea application paths, every tag’s restoration, retention of acquired research slots, eight modeled weeks and unrelated tag preservation.','',
 '**Capability confirmed statically:** the script restrictions on production, construction, conscription and recruitment are absent for the whitelist, the native AI strategy systems are available, and Croatia/Albania’s existing production technologies and templates are retained. This permits factory assignment, lines, construction, training and reinforcement through normal native AI. **Actual engine assignment, construction ticks, recruitment and reinforcement have not been observed**; they remain the user’s test, not a claimed campaign result.','',
 '## 19. Native mechanics and location adaptations','',
 '- Treasury uses native `income_var_temp`/`add_income`, not a fake treasury command, PP substitution or debt. Albanian assistance is $1B at entry and $0.5B at foreign-stockpile access; total support cannot fund all $4.9B contracts immediately.',
 '- Income Growth uses `income_growth_factor`; Business Value uses `business_value_factor`, not the native development-law-only `business_value` field.',
 '- Contracts have the requested fixed negotiated prices instead of an unsupported generic purchase-cost modifier. AI requires an additional $0.25B Albanian / $0.5B Croatian reserve and favors cheap purchases; one shared shipment reservation prevents simultaneous purchases.',
 '- Modest general output replaces an unproven equipment-specific production bonus. Research bonuses use native `infantry_weapons` and `armor` categories, one use at 50%.',
 '- Direct factory rewards use native shared slots, instant construction, before/after `building_level@arms_factory` counters and rejection logging; introduced slots are rolled back on rejection. State ownership/control and capacity must hold. The final Croatian programme adds three more MIL, giving six nationally in the model; Albania’s workshops give two nationally.',
 '- Slavonia is represented within state 109 in this TFR map. Province **3627** is the easternmost native province by actual province-map centroid. It receives two bunker levels, not random forts elsewhere. State 109 receives one infrastructure level up to the native maximum. Membership and real map geometry are recorded and checked.',
 '- Supplied 25 focus and four national-spirit PNGs are converted to established MSGA canvases (95×85 focus, 64×64 idea), DXT5 DDS, using inspected current installed examples. TFR itself uses varied PNG/DDS canvases. Focus and shine sprites are declared; fourteen ideas reuse the four supplied spirit images. Native military/support/truck/tank decision and military-operation category icons are reused. No custom decision graphic or added yellow ring was generated.','',
 '## 20. Validation and smoke result','',
 'Passed on the actual installed mod:','',
 '- `validate_balkan_rearmament.py`: syntax, references, localization, 25 focus prerequisites/durations/tooltips/AI factors, 11 one-time contracts, 14 ideas/modifiers, 29 DDS/GFX, native equipment IDs/DLC design, states, immutable original OOB, factories, exact AI override and producer-lock application paths.',
 '- Short deterministic smoke: both full country focus routes; 12 contract/DLC delivery models; 26 negative cases including insufficient Treasury, cancellation/refund/retry, concurrent purchases, missing German supplier, lost state control and native construction rejection.',
 '- `validate_phase1.py`: existing shared installed-content checks passed.',
 '- `validate_bosnia.py`: existing intervention/settlement regression passed after its pre-existing presentation-only comparison was normalized. Gameplay remains unchanged.','',
 'The smoke test executes actual parsed scripts in a deterministic model; it is **not a HOI4 engine run**. No long campaign, game-window automation, game restart or save edit was performed. Actual AI focus timing/production/construction/recruitment, NSB tank delivery usability, rendering and engine save/load remain untested. Restart the game and use a fresh campaign for starting factories/template verification. No requested script feature remains intentionally unimplemented.','']
 (ROOT/'docs/Balkan-Rearmament-0.16.md').write_text('\n'.join(lines),encoding='utf-8')

def main():
 record=json.loads((ROOT/'docs/balkan_rearmament_sources.json').read_text())
 for file in ['balkan_rearmament_validation.json','balkan_rearmament_phase1_regression.json','balkan_rearmament_bosnia_regression.json']:
  report=json.loads((ROOT/'docs'/file).read_text());assert 'passed' in [report.get(k) for k in ['static_and_model_validation','static_validation']]
  assert Path(report['validated_mod_root']).resolve()==TARGET.resolve(strict=True)
 for relative,digest in record['deployed_sha256'].items():
  installed=TARGET/relative;assert hashlib.sha256(installed.read_bytes()).hexdigest()==digest
  target=SOURCE/relative;assert target.resolve().is_relative_to(SOURCE.resolve());target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(installed,target)
 verify();deployed=json.loads((ROOT/'docs/local_deployment.json').read_text());assert not deployed['copied_absolute_paths'] and not deployed['runtime_only_files']
 hashes=inventory(TARGET);assert hashes==inventory(SOURCE) and len(hashes)==602
 sync={'version':'0.16.0','runtime':str(TARGET),'all_source_runtime_files_identical':True,'file_count':len(hashes),'changed_relative_paths':record['changed_relative_paths'],'deployed_absolute_paths':record['deployed_absolute_paths'],'source_runtime_sha256':hashes,'Workshop_id':'3813570241','validation_order':'LIVE install and three targeted reports passed before source sync','engine_test':'NOT RUN; user game and saves untouched'}
 (ROOT/'docs/balkan_rearmament_sync.json').write_text(json.dumps(sync,indent=2)+'\n');document(record,sync)
 print('LIVE/source: 602 identical files, launcher correct, 0 further deployment changes. Full 20-item report saved.')

if __name__=='__main__':main()
